export interface Book {
  id: string;
  name: string;
  slug: string;
  chapters: number;
  testament: "AT" | "NT";
}

export const BOOKS: Book[] = [
  { id: "gn", name: "Gênesis", slug: "genesis", chapters: 50, testament: "AT" },
  { id: "ex", name: "Êxodo", slug: "exodus", chapters: 40, testament: "AT" },
  { id: "lv", name: "Levítico", slug: "leviticus", chapters: 27, testament: "AT" },
  { id: "nm", name: "Números", slug: "numbers", chapters: 36, testament: "AT" },
  { id: "dt", name: "Deuteronômio", slug: "deuteronomy", chapters: 34, testament: "AT" },
  { id: "js", name: "Josué", slug: "joshua", chapters: 24, testament: "AT" },
  { id: "jg", name: "Juízes", slug: "judges", chapters: 21, testament: "AT" },
  { id: "rt", name: "Rute", slug: "ruth", chapters: 4, testament: "AT" },
  { id: "1sm", name: "1 Samuel", slug: "1samuel", chapters: 31, testament: "AT" },
  { id: "2sm", name: "2 Samuel", slug: "2samuel", chapters: 24, testament: "AT" },
  { id: "1rs", name: "1 Reis", slug: "1kings", chapters: 22, testament: "AT" },
  { id: "2rs", name: "2 Reis", slug: "2kings", chapters: 25, testament: "AT" },
  { id: "1cr", name: "1 Crônicas", slug: "1chronicles", chapters: 29, testament: "AT" },
  { id: "2cr", name: "2 Crônicas", slug: "2chronicles", chapters: 36, testament: "AT" },
  { id: "esd", name: "Esdras", slug: "ezra", chapters: 10, testament: "AT" },
  { id: "ne", name: "Neemias", slug: "nehemiah", chapters: 13, testament: "AT" },
  { id: "tb", name: "Tobias", slug: "tobit", chapters: 14, testament: "AT" },
  { id: "jt", name: "Judite", slug: "judith", chapters: 16, testament: "AT" },
  { id: "et", name: "Ester", slug: "esther", chapters: 16, testament: "AT" },
  { id: "job", name: "Jó", slug: "job", chapters: 42, testament: "AT" },
  { id: "sl", name: "Salmos", slug: "psalms", chapters: 150, testament: "AT" },
  { id: "pv", name: "Provérbios", slug: "proverbs", chapters: 31, testament: "AT" },
  { id: "ecl", name: "Eclesiastes", slug: "ecclesiastes", chapters: 12, testament: "AT" },
  { id: "ct", name: "Cântico dos Cânticos", slug: "songofsolomon", chapters: 8, testament: "AT" },
  { id: "sb", name: "Sabedoria", slug: "wisdom", chapters: 19, testament: "AT" },
  { id: "eclo", name: "Eclesiástico", slug: "sirach", chapters: 51, testament: "AT" },
  { id: "is", name: "Isaías", slug: "isaiah", chapters: 66, testament: "AT" },
  { id: "jr", name: "Jeremias", slug: "jeremiah", chapters: 52, testament: "AT" },
  { id: "lm", name: "Lamentações", slug: "lamentations", chapters: 5, testament: "AT" },
  { id: "br", name: "Baruc", slug: "baruch", chapters: 6, testament: "AT" },
  { id: "ez", name: "Ezequiel", slug: "ezekiel", chapters: 48, testament: "AT" },
  { id: "dn", name: "Daniel", slug: "daniel", chapters: 14, testament: "AT" },
  { id: "os", name: "Oseias", slug: "hosea", chapters: 14, testament: "AT" },
  { id: "jl", name: "Joel", slug: "joel", chapters: 4, testament: "AT" },
  { id: "am", name: "Amós", slug: "amos", chapters: 9, testament: "AT" },
  { id: "ab", name: "Abdias", slug: "obadiah", chapters: 1, testament: "AT" },
  { id: "jn", name: "Jonas", slug: "jonah", chapters: 4, testament: "AT" },
  { id: "mq", name: "Miqueias", slug: "micah", chapters: 7, testament: "AT" },
  { id: "na", name: "Naum", slug: "nahum", chapters: 3, testament: "AT" },
  { id: "hc", name: "Habacuque", slug: "habakkuk", chapters: 3, testament: "AT" },
  { id: "sf", name: "Sofonias", slug: "zephaniah", chapters: 3, testament: "AT" },
  { id: "ag", name: "Ageu", slug: "haggai", chapters: 2, testament: "AT" },
  { id: "zc", name: "Zacarias", slug: "zechariah", chapters: 14, testament: "AT" },
  { id: "ml", name: "Malaquias", slug: "malachi", chapters: 3, testament: "AT" },
  { id: "1mc", name: "1 Macabeus", slug: "1maccabees", chapters: 16, testament: "AT" },
  { id: "2mc", name: "2 Macabeus", slug: "2maccabees", chapters: 15, testament: "AT" },
  { id: "mt", name: "Mateus", slug: "matthew", chapters: 28, testament: "NT" },
  { id: "mc", name: "Marcos", slug: "mark", chapters: 16, testament: "NT" },
  { id: "lc", name: "Lucas", slug: "luke", chapters: 24, testament: "NT" },
  { id: "jo", name: "João", slug: "john", chapters: 21, testament: "NT" },
  { id: "at", name: "Atos", slug: "acts", chapters: 28, testament: "NT" },
  { id: "rm", name: "Romanos", slug: "romans", chapters: 16, testament: "NT" },
  { id: "1cor", name: "1 Coríntios", slug: "1corinthians", chapters: 16, testament: "NT" },
  { id: "2cor", name: "2 Coríntios", slug: "2corinthians", chapters: 13, testament: "NT" },
  { id: "gl", name: "Gálatas", slug: "galatians", chapters: 6, testament: "NT" },
  { id: "ef", name: "Efésios", slug: "ephesians", chapters: 6, testament: "NT" },
  { id: "fl", name: "Filipenses", slug: "philippians", chapters: 4, testament: "NT" },
  { id: "cl", name: "Colossenses", slug: "colossians", chapters: 4, testament: "NT" },
  { id: "1ts", name: "1 Tessalonicenses", slug: "1thessalonians", chapters: 5, testament: "NT" },
  { id: "2ts", name: "2 Tessalonicenses", slug: "2thessalonians", chapters: 3, testament: "NT" },
  { id: "1tm", name: "1 Timóteo", slug: "1timothy", chapters: 6, testament: "NT" },
  { id: "2tm", name: "2 Timóteo", slug: "2timothy", chapters: 4, testament: "NT" },
  { id: "tt", name: "Tito", slug: "titus", chapters: 3, testament: "NT" },
  { id: "fm", name: "Filemom", slug: "philemon", chapters: 1, testament: "NT" },
  { id: "hb", name: "Hebreus", slug: "hebrews", chapters: 13, testament: "NT" },
  { id: "tg", name: "Tiago", slug: "james", chapters: 5, testament: "NT" },
  { id: "1pe", name: "1 Pedro", slug: "1peter", chapters: 5, testament: "NT" },
  { id: "2pe", name: "2 Pedro", slug: "2peter", chapters: 3, testament: "NT" },
  { id: "1jo", name: "1 João", slug: "1john", chapters: 5, testament: "NT" },
  { id: "2jo", name: "2 João", slug: "2john", chapters: 1, testament: "NT" },
  { id: "3jo", name: "3 João", slug: "3john", chapters: 1, testament: "NT" },
  { id: "jd", name: "Judas", slug: "jude", chapters: 1, testament: "NT" },
  { id: "ap", name: "Apocalipse", slug: "revelation", chapters: 22, testament: "NT" },
];

export function getBook(id: string): Book | undefined {
  return BOOKS.find((b) => b.id === id);
}
