export interface Book {
  id: string;
  name: string;
  slug: string;
  chapters: number;
  testament: "AT" | "NT";
}

export const BOOKS: Book[] = [
  { id: "gn", name: "Gênesis", slug: "genesis", chapters: 50, testament: "AT" },
  { id: "ex", name: "Êxodo", slug: "exodo", chapters: 40, testament: "AT" },
  { id: "lv", name: "Levítico", slug: "levitico", chapters: 27, testament: "AT" },
  { id: "nm", name: "Números", slug: "numeros", chapters: 36, testament: "AT" },
  { id: "dt", name: "Deuteronômio", slug: "deuteronomio", chapters: 34, testament: "AT" },
  { id: "js", name: "Josué", slug: "josue", chapters: 24, testament: "AT" },
  { id: "jg", name: "Juízes", slug: "juizes", chapters: 21, testament: "AT" },
  { id: "rt", name: "Rute", slug: "rute", chapters: 4, testament: "AT" },
  { id: "1sm", name: "1 Samuel", slug: "1-samuel", chapters: 31, testament: "AT" },
  { id: "2sm", name: "2 Samuel", slug: "2-samuel", chapters: 24, testament: "AT" },
  { id: "1rs", name: "1 Reis", slug: "1-reis", chapters: 22, testament: "AT" },
  { id: "2rs", name: "2 Reis", slug: "2-reis", chapters: 25, testament: "AT" },
  { id: "1cr", name: "1 Crônicas", slug: "1-cronicas", chapters: 29, testament: "AT" },
  { id: "2cr", name: "2 Crônicas", slug: "2-cronicas", chapters: 36, testament: "AT" },
  { id: "esd", name: "Esdras", slug: "esdras", chapters: 10, testament: "AT" },
  { id: "ne", name: "Neemias", slug: "neemias", chapters: 13, testament: "AT" },
  { id: "tb", name: "Tobias", slug: "tobias", chapters: 14, testament: "AT" },
  { id: "jt", name: "Judite", slug: "judite", chapters: 16, testament: "AT" },
  { id: "et", name: "Ester", slug: "ester", chapters: 16, testament: "AT" },
  { id: "job", name: "Jó", slug: "job", chapters: 42, testament: "AT" },
  { id: "sl", name: "Salmos", slug: "salmos", chapters: 150, testament: "AT" },
  { id: "pv", name: "Provérbios", slug: "proverbios", chapters: 31, testament: "AT" },
  { id: "ecl", name: "Eclesiastes", slug: "eclesiastes", chapters: 12, testament: "AT" },
  { id: "ct", name: "Cântico dos Cânticos", slug: "cantico", chapters: 8, testament: "AT" },
  { id: "sb", name: "Sabedoria", slug: "sabedoria", chapters: 19, testament: "AT" },
  { id: "eclo", name: "Eclesiástico", slug: "eclesiastico", chapters: 51, testament: "AT" },
  { id: "is", name: "Isaías", slug: "isaias", chapters: 66, testament: "AT" },
  { id: "jr", name: "Jeremias", slug: "jeremias", chapters: 52, testament: "AT" },
  { id: "lm", name: "Lamentações", slug: "lamentacoes", chapters: 5, testament: "AT" },
  { id: "br", name: "Baruc", slug: "baruc", chapters: 6, testament: "AT" },
  { id: "ez", name: "Ezequiel", slug: "ezequiel", chapters: 48, testament: "AT" },
  { id: "dn", name: "Daniel", slug: "daniel", chapters: 14, testament: "AT" },
  { id: "os", name: "Oseias", slug: "oseias", chapters: 14, testament: "AT" },
  { id: "jl", name: "Joel", slug: "joel", chapters: 4, testament: "AT" },
  { id: "am", name: "Amós", slug: "amos", chapters: 9, testament: "AT" },
  { id: "ab", name: "Abdias", slug: "abdias", chapters: 1, testament: "AT" },
  { id: "jn", name: "Jonas", slug: "jonas", chapters: 4, testament: "AT" },
  { id: "mq", name: "Miqueias", slug: "miqueias", chapters: 7, testament: "AT" },
  { id: "na", name: "Naum", slug: "naum", chapters: 3, testament: "AT" },
  { id: "hc", name: "Habacuque", slug: "habacuque", chapters: 3, testament: "AT" },
  { id: "sf", name: "Sofonias", slug: "sofonias", chapters: 3, testament: "AT" },
  { id: "ag", name: "Ageu", slug: "ageu", chapters: 2, testament: "AT" },
  { id: "zc", name: "Zacarias", slug: "zacarias", chapters: 14, testament: "AT" },
  { id: "ml", name: "Malaquias", slug: "malaquias", chapters: 3, testament: "AT" },
  { id: "1mc", name: "1 Macabeus", slug: "1-macabeus", chapters: 16, testament: "AT" },
  { id: "2mc", name: "2 Macabeus", slug: "2-macabeus", chapters: 15, testament: "AT" },
  { id: "mt", name: "Mateus", slug: "mateus", chapters: 28, testament: "NT" },
  { id: "mc", name: "Marcos", slug: "marcos", chapters: 16, testament: "NT" },
  { id: "lc", name: "Lucas", slug: "lucas", chapters: 24, testament: "NT" },
  { id: "jo", name: "João", slug: "joao", chapters: 21, testament: "NT" },
  { id: "at", name: "Atos", slug: "atos", chapters: 28, testament: "NT" },
  { id: "rm", name: "Romanos", slug: "romanos", chapters: 16, testament: "NT" },
  { id: "1cor", name: "1 Coríntios", slug: "1-corintios", chapters: 16, testament: "NT" },
  { id: "2cor", name: "2 Coríntios", slug: "2-corintios", chapters: 13, testament: "NT" },
  { id: "gl", name: "Gálatas", slug: "galatas", chapters: 6, testament: "NT" },
  { id: "ef", name: "Efésios", slug: "efesios", chapters: 6, testament: "NT" },
  { id: "fl", name: "Filipenses", slug: "filipenses", chapters: 4, testament: "NT" },
  { id: "cl", name: "Colossenses", slug: "colossenses", chapters: 4, testament: "NT" },
  { id: "1ts", name: "1 Tessalonicenses", slug: "1-tessalonicenses", chapters: 5, testament: "NT" },
  { id: "2ts", name: "2 Tessalonicenses", slug: "2-tessalonicenses", chapters: 3, testament: "NT" },
  { id: "1tm", name: "1 Timóteo", slug: "1-timoteo", chapters: 6, testament: "NT" },
  { id: "2tm", name: "2 Timóteo", slug: "2-timoteo", chapters: 4, testament: "NT" },
  { id: "tt", name: "Tito", slug: "tito", chapters: 3, testament: "NT" },
  { id: "fm", name: "Filemom", slug: "filemom", chapters: 1, testament: "NT" },
  { id: "hb", name: "Hebreus", slug: "hebreus", chapters: 13, testament: "NT" },
  { id: "tg", name: "Tiago", slug: "tiago", chapters: 5, testament: "NT" },
  { id: "1pe", name: "1 Pedro", slug: "1-pedro", chapters: 5, testament: "NT" },
  { id: "2pe", name: "2 Pedro", slug: "2-pedro", chapters: 3, testament: "NT" },
  { id: "1jo", name: "1 João", slug: "1-joao", chapters: 5, testament: "NT" },
  { id: "2jo", name: "2 João", slug: "2-joao", chapters: 1, testament: "NT" },
  { id: "3jo", name: "3 João", slug: "3-joao", chapters: 1, testament: "NT" },
  { id: "jd", name: "Judas", slug: "judas", chapters: 1, testament: "NT" },
  { id: "ap", name: "Apocalipse", slug: "apocalipse", chapters: 22, testament: "NT" },
];

export function getBook(id: string): Book | undefined {
  return BOOKS.find((b) => b.id === id);
}
