-- ==========================================================
-- Migration: Create Bible schema with multi-version support
-- Version: 2026-06-30_001
-- 
-- Cria o schema relacional completo da Bíblia, preparado para
-- múltiplas traduções (Ave-Maria inicialmente) com Full Text
-- Search em português.
-- ==========================================================

-- 1. Versões da Bíblia
create table if not exists public.bible_versions (
    id          bigint generated by default as identity primary key,
    slug        varchar(20)  not null unique,
    name        varchar(100) not null,
    language    varchar(10)  not null default 'pt',
    is_default  boolean      not null default false,
    description text,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

comment on table public.bible_versions is 'Traduções/Versões da Bíblia disponíveis';
comment on column public.bible_versions.slug is 'Identificador URL: "ave-maria", "nvi", "kjv"';
comment on column public.bible_versions.is_default is 'Apenas uma versão pode ser default';

-- 2. Livros
create table if not exists public.bible_books (
    id              bigint generated by default as identity primary key,
    version_id      bigint       not null references public.bible_versions(id),
    testament       char(2)      not null check (testament in ('AT', 'NT')),
    abbreviation    varchar(10)  not null,
    slug            varchar(60)  not null,
    name            varchar(100) not null,
    position        smallint     not null,
    chapters_count  smallint     not null default 0,
    created_at      timestamptz  not null default now(),
    updated_at      timestamptz  not null default now(),
    unique(version_id, abbreviation),
    unique(version_id, slug)
);

comment on table public.bible_books is 'Livros da Bíblia, por versão';

create index idx_bible_books_testament on public.bible_books (version_id, testament, position);

-- 3. Capítulos
create table if not exists public.bible_chapters (
    id            bigint generated by default as identity primary key,
    book_id       bigint   not null references public.bible_books(id) on delete cascade,
    number        smallint not null,
    verses_count  smallint not null default 0,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    unique(book_id, number)
);

comment on table public.bible_chapters is 'Capítulos de cada livro';

create index idx_bible_chapters_book on public.bible_chapters (book_id, number);

-- 4. Versículos (com Full Text Search)
create table if not exists public.bible_verses (
    id            bigint generated by default as identity primary key,
    book_id       bigint   not null references public.bible_books(id) on delete cascade,
    chapter_id    bigint   not null references public.bible_chapters(id) on delete cascade,
    number        smallint not null,
    text          text     not null,
    search_vector tsvector generated always as (to_tsvector('portuguese', text)) stored,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    unique(chapter_id, number)
);

comment on table public.bible_verses is 'Versículos com suporte a Full Text Search em português';

-- Índices
create index idx_bible_verses_book on public.bible_verses (book_id, chapter_id, number);
create index idx_bible_verses_chapter on public.bible_verses (chapter_id, number);

-- GIN index para Full Text Search
create index if not exists idx_bible_verses_fts
    on public.bible_verses
    using gin (search_vector);

-- Trigger: atualiza updated_at automaticamente
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger trg_bible_versions_updated_at
    before update on public.bible_versions
    for each row execute function public.set_updated_at();

create trigger trg_bible_books_updated_at
    before update on public.bible_books
    for each row execute function public.set_updated_at();

create trigger trg_bible_chapters_updated_at
    before update on public.bible_chapters
    for each row execute function public.set_updated_at();

create trigger trg_bible_verses_updated_at
    before update on public.bible_verses
    for each row execute function public.set_updated_at();

-- View: versículos com metadados (para consultas frequentes)
create or replace view public.vw_bible_verses as
select
    v.id           as verse_id,
    v.number       as verse_number,
    v.text         as verse_text,
    c.number       as chapter_number,
    c.verses_count as chapter_verses,
    b.abbreviation as book_abbrev,
    b.slug         as book_slug,
    b.name         as book_name,
    b.testament,
    b.position     as book_position,
    v.search_vector
from public.bible_verses v
join public.bible_chapters c on c.id = v.chapter_id
join public.bible_books b on b.id = v.book_id;

-- View: capítulos com totais
create or replace view public.vw_bible_chapters as
select
    c.id,
    b.slug         as book_slug,
    b.name         as book_name,
    b.abbreviation as book_abbrev,
    c.number       as chapter_number,
    c.verses_count,
    b.testament
from public.bible_chapters c
join public.bible_books b on b.id = c.book_id;
