-- ==========================================================
-- MIGRAÇÃO COMPLETA — Sejais Santo 2.0.0
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase
-- ==========================================================

-- ==========================================================
-- 1. BIBLE SCHEMA (tabelas + views + FTS + triggers)
-- ==========================================================

create table if not exists public.bible_versions (
    id          bigint generated by default as identity primary key,
    slug        varchar(20)  not null unique,
    name        varchar(100) not null,
    language    varchar(10)  not null default 'pt',
    is_default  boolean      not null default false,
    description text,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

comment on table public.bible_versions is 'Traduções/Versões da Bíblia disponíveis';
comment on column public.bible_versions.slug is 'Identificador URL: "ave-maria", "nvi", "kjv"';
comment on column public.bible_versions.is_default is 'Apenas uma versão pode ser default';

create table if not exists public.bible_books (
    id              bigint generated by default as identity primary key,
    version_id      bigint       not null references public.bible_versions(id),
    testament       char(2)      not null check (testament in ('AT', 'NT')),
    abbreviation    varchar(10)  not null,
    slug            varchar(60)  not null,
    name            varchar(100) not null,
    position        smallint     not null,
    chapters_count  smallint     not null default 0,
    created_at      timestamptz  not null default now(),
    updated_at      timestamptz  not null default now(),
    unique(version_id, abbreviation),
    unique(version_id, slug)
);

comment on table public.bible_books is 'Livros da Bíblia, por versão';
create index if not exists idx_bible_books_testament on public.bible_books (version_id, testament, position);

create table if not exists public.bible_chapters (
    id            bigint generated by default as identity primary key,
    book_id       bigint   not null references public.bible_books(id) on delete cascade,
    number        smallint not null,
    verses_count  smallint not null default 0,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    unique(book_id, number)
);

comment on table public.bible_chapters is 'Capítulos de cada livro';
create index if not exists idx_bible_chapters_book on public.bible_chapters (book_id, number);

create table if not exists public.bible_verses (
    id            bigint generated by default as identity primary key,
    book_id       bigint   not null references public.bible_books(id) on delete cascade,
    chapter_id    bigint   not null references public.bible_chapters(id) on delete cascade,
    number        smallint not null,
    text          text     not null,
    search_vector tsvector generated always as (to_tsvector('portuguese', text)) stored,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now(),
    unique(chapter_id, number)
);

comment on table public.bible_verses is 'Versículos com suporte a Full Text Search em português';
create index if not exists idx_bible_verses_book on public.bible_verses (book_id, chapter_id, number);
create index if not exists idx_bible_verses_chapter on public.bible_verses (chapter_id, number);
create index if not exists idx_bible_verses_fts on public.bible_verses using gin (search_vector);

-- Trigger function: updated_at automático
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_bible_versions_updated_at on public.bible_versions;
create trigger trg_bible_versions_updated_at
    before update on public.bible_versions
    for each row execute function public.set_updated_at();

drop trigger if exists trg_bible_books_updated_at on public.bible_books;
create trigger trg_bible_books_updated_at
    before update on public.bible_books
    for each row execute function public.set_updated_at();

drop trigger if exists trg_bible_chapters_updated_at on public.bible_chapters;
create trigger trg_bible_chapters_updated_at
    before update on public.bible_chapters
    for each row execute function public.set_updated_at();

drop trigger if exists trg_bible_verses_updated_at on public.bible_verses;
create trigger trg_bible_verses_updated_at
    before update on public.bible_verses
    for each row execute function public.set_updated_at();

-- View: versículos com metadados
create or replace view public.vw_bible_verses as
select
    v.id           as verse_id,
    v.number       as verse_number,
    v.text         as verse_text,
    c.number       as chapter_number,
    c.verses_count as chapter_verses,
    b.abbreviation as book_abbrev,
    b.slug         as book_slug,
    b.name         as book_name,
    b.testament,
    b.position     as book_position,
    v.search_vector
from public.bible_verses v
join public.bible_chapters c on c.id = v.chapter_id
join public.bible_books b on b.id = v.book_id;

-- View: capítulos com totais
create or replace view public.vw_bible_chapters as
select
    c.id,
    b.slug         as book_slug,
    b.name         as book_name,
    b.abbreviation as book_abbrev,
    c.number       as chapter_number,
    c.verses_count,
    b.testament
from public.bible_chapters c
join public.bible_books b on b.id = c.book_id;

-- ==========================================================
-- 2. VERSES (versículos do usuário)
-- ==========================================================

create table if not exists public.verses (
  id text primary key,
  text text,
  note text,
  author_email text,
  user_id text,
  scheduled_at timestamptz,
  created_at timestamptz default now(),
  raw jsonb
);

-- ==========================================================
-- 3. DAILY GOSPEL (cache do evangelho do dia)
-- ==========================================================

create table if not exists public.daily_gospel (
  id serial primary key,
  date text not null unique,
  referencia text not null,
  texto text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_daily_gospel_date on public.daily_gospel (date);

-- ==========================================================
-- 4. DAILY GOSPEL — colunas litúrgicas
-- ==========================================================

alter table public.daily_gospel add column if not exists liturgical_season varchar(20);
alter table public.daily_gospel add column if not exists sunday_cycle char(1);
alter table public.daily_gospel add column if not exists ferial_cycle char(2);
alter table public.daily_gospel add column if not exists week_number smallint;
alter table public.daily_gospel add column if not exists pericope varchar(40);
alter table public.daily_gospel add column if not exists book_abbrev varchar(10);
alter table public.daily_gospel add column if not exists liturgical_key varchar(30);

create index if not exists idx_daily_gospel_season on public.daily_gospel (liturgical_season);
create index if not exists idx_daily_gospel_cycle on public.daily_gospel (sunday_cycle);

-- ==========================================================
-- 5. BIBLE CACHE (legado — será removido futuramente)
-- ==========================================================

create table if not exists public.bible_cache (
  id serial primary key,
  reference text not null unique,
  book_slug text not null,
  chapter smallint not null,
  data jsonb not null,
  created_at timestamptz default now()
);

create index if not exists idx_bible_cache_reference on public.bible_cache (reference);

-- ==========================================================
-- 6. RLS POLICIES (segurança de todas as tabelas)
-- ==========================================================

-- BIBLE VERSIONS
alter table if exists public.bible_versions enable row level security;
drop policy if exists "Bible versions are publicly readable" on public.bible_versions;
create policy "Bible versions are publicly readable"
    on public.bible_versions for select using (true);
drop policy if exists "Only service role can manage bible versions" on public.bible_versions;
create policy "Only service role can manage bible versions"
    on public.bible_versions for all to service_role using (true) with check (true);

-- BIBLE BOOKS
alter table if exists public.bible_books enable row level security;
drop policy if exists "Bible books are publicly readable" on public.bible_books;
create policy "Bible books are publicly readable"
    on public.bible_books for select using (true);
drop policy if exists "Only service role can manage bible books" on public.bible_books;
create policy "Only service role can manage bible books"
    on public.bible_books for all to service_role using (true) with check (true);

-- BIBLE CHAPTERS
alter table if exists public.bible_chapters enable row level security;
drop policy if exists "Bible chapters are publicly readable" on public.bible_chapters;
create policy "Bible chapters are publicly readable"
    on public.bible_chapters for select using (true);
drop policy if exists "Only service role can manage bible chapters" on public.bible_chapters;
create policy "Only service role can manage bible chapters"
    on public.bible_chapters for all to service_role using (true) with check (true);

-- BIBLE VERSES
alter table if exists public.bible_verses enable row level security;
drop policy if exists "Bible verses are publicly readable" on public.bible_verses;
create policy "Bible verses are publicly readable"
    on public.bible_verses for select using (true);
drop policy if exists "Only service role can manage bible verses" on public.bible_verses;
create policy "Only service role can manage bible verses"
    on public.bible_verses for all to service_role using (true) with check (true);

-- DAILY GOSPEL
alter table if exists public.daily_gospel enable row level security;
drop policy if exists "Anyone can read daily gospel" on public.daily_gospel;
create policy "Anyone can read daily gospel"
    on public.daily_gospel for select using (true);
drop policy if exists "Only service role can manage daily gospel" on public.daily_gospel;
create policy "Only service role can manage daily gospel"
    on public.daily_gospel for all to service_role using (true) with check (true);

-- VERSES (conteúdo do usuário — RLS por auth.uid)
alter table if exists public.verses enable row level security;
drop policy if exists "Users can read own verses" on public.verses;
create policy "Users can read own verses"
    on public.verses for select using (auth.uid() = user_id::uuid);
drop policy if exists "Users can create own verses" on public.verses;
create policy "Users can create own verses"
    on public.verses for insert with check (auth.uid() = user_id::uuid);
drop policy if exists "Users can delete own verses" on public.verses;
create policy "Users can delete own verses"
    on public.verses for delete using (auth.uid() = user_id::uuid);

-- BIBLE CACHE (legado)
alter table if exists public.bible_cache enable row level security;
drop policy if exists "Bible cache is publicly readable" on public.bible_cache;
create policy "Bible cache is publicly readable"
    on public.bible_cache for select using (true);
drop policy if exists "Only service role can manage bible cache" on public.bible_cache;
create policy "Only service role can manage bible cache"
    on public.bible_cache for all to service_role using (true) with check (true);
